pipeline:
  docker:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying-components
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  test:
    image:  quay.io/uswitch/terrafying-components:${DRONE_COMMIT_SHA}
    commands:
      - bundle exec rspec spec/
    when:
      event: push

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying-components
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: master

  tag:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying-components
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
      branch: master
