pipeline:
  test:
    image: ruby:2.5.1
    commands:
      - bundle install
      - bundle exec rake
    when:
      event: push

  docker:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying-components
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying-components
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: master

  docker-tag:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying-components
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
      branch: master


  gem-tag:
    image: ruby:2.4
    secrets: [RUBYGEMS_API_KEY]
    commands:
      - bundle install
      - sed -i 's/0\.0\.0/${DRONE_TAG}/' lib/terrafying/components/version.rb
      - gem build terrafying_components.gemspec
      - bundle exec rake push
    when:
      event: tag
      branch: master
